name: sync fork

on:
  workflow_call:
    secrets:
      fork:
        required: true
      upstream:
        required: true
      token:
        required: true

jobs:
  sync:
    name: sync fork
    runs-on: ubuntu-latest
    steps:
      - name: input fork
        uses: KyoriPowered/action-regex-match@v4
        id: fork
        with:
          text: ${{ secrets.fork }}
          regex: '^([^\/]+\/[^\/]+)\/(.+)$'
      - name: input upstream
        uses: KyoriPowered/action-regex-match@v4
        id: upstream
        with:
          text: ${{ secrets.upstream }}
          regex: '^([^\/]+\/[^\/]+)\/(.+)$'
      - name: checkout fork
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.fork.outputs.group1 }}
          ref: ${{ steps.fork.outputs.group2 }}
          token: ${{ secrets.token }}
      - name: sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ${{ steps.upstream.outputs.group1 }}
          upstream_sync_branch: ${{ steps.upstream.outputs.group2 }}
          target_sync_branch: ${{ steps.fork.outputs.group2 }}
          git_config_pull_rebase: true
          target_branch_push_args: --force-with-lease
