name: fgc

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  master:
    uses: ./.github/workflows/_sync.yml
    secrets:
      fork-name: ${{ secrets.FGC_FORK }}
      fork-branch: master
      upstream-name: ${{ secrets.FGC_UPSTREAM }}
      upstream-branch: master
      token: ${{ secrets.PAT }}
