name: rss-bridge

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  master:
    uses: ./.github/workflows/_sync.yml
    secrets:
      fork: User123698745/rss-bridge/master
      upstream: RSS-Bridge/rss-bridge/master
      token: ${{ secrets.PAT }}

  fork-master:
    uses: ./.github/workflows/_sync.yml
    secrets:
      fork: User123698745/rss-bridge/fork-master
      upstream: RSS-Bridge/rss-bridge/master
      token: ${{ secrets.PAT }}
