name: rss-bridge

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  master:
    uses: ./.github/workflows/_sync.yml
    secrets:
      fork-name: User123698745/rss-bridge
      fork-branch: master
      upstream-name: RSS-Bridge/rss-bridge
      upstream-branch: master
      token: ${{ secrets.PAT }}
